export class DevisData {
	projet: string;
	cpProjet: number;
	villeProjet: string;
	typeProjet: string;
	etat: string;
	usage: string;
	situationActuelle: string;
	avancement: string;
	civilite: string;
	nom: string;
	prenom: string;
	cp: number;
	ville: string;
	preference: string;
	telPort: number;
	telFixe: number;
	mail: string;
	montant: number;
	notaire: number;
	caution:number;
	budget: number;
};